# Generated by Django 5.2.1 on 2025-08-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCTADD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsss', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=75)),
                ('img1', models.FileField(upload_to='databook/')),
                ('img2', models.FileField(upload_to='databook/')),
                ('img3', models.FileField(upload_to='databook/')),
                ('descriptions', models.CharField(max_length=50)),
                ('cutprice', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
